apiVersion: v1
kind: Pod
metadata:
  name: my-workflow
spec:
  containers:
  - name: app
    image: redabona/datacraft-k8s-workshop:toy-workflow
    volumeMounts:
    - mountPath: /data
      name: pv0001
    ports:
    - containerPort: 80
    imagePullPolicy: Always
  volumes:
      - name: pv0001
        hostPath:
            path: /data/pv0001
  
